### PR TITLE
Update to v1.3.7

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
@conda-forge-admin, please rerender

**Comment by sebastian-luna-valero** [comment]
@mariojmdavid thanks for updating the code in the `master` branch.

Could you please make a new `udocker` release `v1.3.7` so we can update the conda package?

Many thanks!

**Comment by mariojmdavid** [comment]
I just made the release 1.3.7 into the repository

**Comment by sebastian-luna-valero** [comment]
Great, working now, thanks!

**Pull request merged**
